### ISSUE TITLE
Some unit tests failed after fixing 85

### ISSUE THREAD

**Issue by cjcodeproj** [cjcodeproj/medialibrary#95]
Two unit tests were failing after fixing issue #85 

```
$ PYTHONPATH=src python -m unittest 
...........F...........................................F.....................................
======================================================================
FAIL: test_title_sort_title (test.media.data.media.contents.generic.test_catalog.TestTitle)
Assert Title instance has correct sort_value.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chrisj/wpython/medialibrary/test/media/data/media/contents/generic/test_catalog.py", line 141, in test_title_sort_title
    self.assertEqual(self.movie.title.sort_title, "river_turns_inward__a")
AssertionError: 'river_turns_inward_+a' != 'river_turns_inward__a'
- river_turns_inward_+a
?                    ^
+ river_turns_inward__a
?                    ^


======================================================================
FAIL: test_movie_unique_key (test.media.data.media.contents.movie.test_internal.TestMovie)
Assert the unique key value for a given movie.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chrisj/wpython/medialibrary/test/media/data/media/contents/movie/test_internal.py", line 107, in test_movie_unique_key
    self.assertEqual(self.movie.unique_key,
AssertionError: 'river_turns_inward_+a-0000-1' != 'river_turns_inward__a-0000-1'
- river_turns_inward_+a-0000-1
?                    ^
+ river_turns_inward__a-0000-1
?                    ^


----------------------------------------------------------------------
Ran 93 tests in 0.021s

FAILED (failures=2)
```

Both tests should have been updated to reflect that the plus character is used for the prefix character in an article sort name.

**Comment by cjcodeproj** [comment]
Commit:

https://github.com/cjcodeproj/medialibrary/commit/79048cc00ddea9c6a95b156c13af22d534801692
